# -*- coding: utf-8 -*-
"""Movie_Recommendation_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s347jG-U-in9vCBYW7JM4Tgc6v2exiey

Movie Recommendation System using Machine Learning

1.Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

""" 2. Load Dataset"""

movies = pd.read_csv("/content/tmdb_5000_movies.csv")
credits = pd.read_csv("/content/tmdb_5000_credits.csv")

"""3. Data Inspection"""

movies.head()

credits.head()

movies.shape

credits.shape

movies.columns

credits.columns

movies["title"].head()

credits["title"].head()

"""4. Merge Datasets"""

movies = movies.merge(credits, on="title")

movies.head()

movies.shape

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

movies.head()

"""5. Data Cleaning"""

movies.isnull().sum()

movies.dropna(inplace=True)

movies.isnull().sum()

movies.duplicated().sum()

movies.drop_duplicates(inplace=True)

""" 6. Feature Engineering"""

movies["tags"] = movies["overview"] + movies["genres"] + movies["keywords"] + movies["cast"] + movies["crew"]

new_df = movies[["movie_id", "title", "tags"]]

new_df.head()

new_df["tags"] = new_df["tags"].apply(lambda x: x.lower())

new_df.head()

""" 7. Text Vectorization"""

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()

vectors.shape

""" 8. Cosine Similarity"""

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

similarity.shape

import numpy as np

""" 9. Recommendation Function"""

def recommend(movie):
    movie = movie.lower()

    # Find the movie index
    matching_movies = new_df[new_df['title'].str.lower() == movie]

    if matching_movies.empty:
        print("Movie not found!")
        return

    movie_index = matching_movies.index[0]

    # Get similarity scores
    distances = similarity[movie_index]

    # Sort movies by similarity
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    print("Recommended Movies:\n")

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

""" 10. Testing"""

recommend("Avatar")

recommend("The Dark Knight")

"""Conclusion

In this project, a content-based Movie Recommendation System was developed using Python and Scikit-learn.

The recommendation engine suggests similar movies by comparing genres, keywords, cast, crew, and movie overviews using CountVectorizer and Cosine Similarity.

This project demonstrates how machine learning can be used to build recommendation systems similar to those used by streaming platforms.
"""